$background = rgb(050000)
$foreground = rgb(E8CCB6)
$color0 = rgb(0F0A03)
$color1 = rgb(5D4126)
$color2 = rgb(694525)
$color3 = rgb(764924)
$color4 = rgb(824E23)
$color5 = rgb(8E5222)
$color6 = rgb(8F5222)
$color7 = rgb(D6AE8E)
$color8 = rgb(967963)
$color9 = rgb(7C5633)
$color10 = rgb(8C5C31)
$color11 = rgb(9D6230)
$color12 = rgb(AE672F)
$color13 = rgb(BE6D2E)
$color14 = rgb(BE6D2E)
$color15 = rgb(D6AE8E)
