# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(000004)
$foreground = rgb(D0D2D6)
$color0 = rgb(000004)
$color1 = rgb(292D36)
$color2 = rgb(51555E)
$color3 = rgb(535861)
$color4 = rgb(535861)
$color5 = rgb(535861)
$color6 = rgb(5A5E68)
$color7 = rgb(B3B6BD)
$color8 = rgb(7D7F84)
$color9 = rgb(363C48)
$color10 = rgb(6B717D)
$color11 = rgb(6F7581)
$color12 = rgb(6F7581)
$color13 = rgb(6F7581)
$color14 = rgb(787E8B)
$color15 = rgb(B3B6BD)
