$background = rgb(030000)
$foreground = rgb(FBF8F2)
$color0 = rgb(030000)
$color1 = rgb(3F382C)
$color2 = rgb(184C64)
$color3 = rgb(69533E)
$color4 = rgb(605A4F)
$color5 = rgb(7D776E)
$color6 = rgb(B7B0A3)
$color7 = rgb(F1ECE4)
$color8 = rgb(A9A59F)
$color9 = rgb(544B3B)
$color10 = rgb(206586)
$color11 = rgb(8C6E53)
$color12 = rgb(80786A)
$color13 = rgb(A79F93)
$color14 = rgb(F4EAD9)
$color15 = rgb(F1ECE4)
