# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #D0D2D6
background         #000004
cursor             #9EA2AA

active_tab_foreground     #000004
active_tab_background     #D0D2D6
inactive_tab_foreground   #D0D2D6
inactive_tab_background   #000004

active_border_color   #D0D2D6
inactive_border_color #000004
bell_border_color     #292D36

color0      #000004
color1		#292D36
color2		#51555E
color3		#535861
color4		#535861
color5		#535861
color6		#5A5E68
color7		#B3B6BD
color8		#7D7F84
color9		#363C48
color10		#6B717D
color11		#6F7581
color12		#6F7581
color13		#6F7581
color14		#787E8B
color15		#B3B6BD
